name: Monitor Entire EKS Cluster with Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Required for requesting the JWT
  contents: read  # Required for actions/checkout

env:
  AWS_REGION: eu-west-1
  EKS_CLUSTER_NAME: nx-poc-cluster

jobs:
  snyk-monitor:
    name: Monitor Entire EKS Cluster with Snyk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from O
